x-common-config: &common-config
  networks:
    - app_network
  env_file:
    - .env

services:
  frontend:
    <<: *common-config
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  # Service name - referenced in other services as hostname "db"
  db:
    <<: *common-config
    image: postgres:15-alpine  # Official PostgreSQL image using Alpine Linux
    restart: always  # Automatic restart policy
    healthcheck: # to ensure the database is ready before starting the application
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]  # Uses PostgreSQL's connection check
      interval: 10s  # Check frequency
      timeout: 5s  # Max time per check
      retries: 5 # Allowed failures before "unhealthy"
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis for Celery broker and cache
  redis:
    <<: *common-config
    image: redis:7-alpine
    command:
      - redis-server
      - --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django
  backend:
    <<: *common-config
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend  # Named image to be reused by celery_worker
    command: python manage.py runserver 0.0.0.0:8000 # start the Django development server
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media

  celery_worker:
    <<: *common-config
    image: backend  # Reusing the same image as backend
    command: celery -A config.celery worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    healthcheck: # ensure services are properly running
      test: ["CMD", "celery", "-A", "config.celery", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  app_network:
    driver: bridge