import { JobPosition } from '@/types';

export const JOB_POSITIONS: JobPosition[] = [
  {
    id: 'eng-sr-fullstack',
    title: 'Senior Full-Stack Fintech Engineer',
    department: 'Engineering',
    location: 'Makati City, Metro Manila (or Hybrid/Remote PH)',
    type: 'Full-time',
    workplace: 'Remote',
    salaryRange: '₱130,000 - ₱180,000 / mo + Equity',
    experience: '5+ years',
    postedDate: 'August 2026',
    featured: true,
    description: 'Lead the architecture and real-time execution of our core OLAP (Online Loan Application Processing) decision engine, building high-throughput financial pipelines and responsive React interfaces.',
    responsibilities: [
      'Architect robust TypeScript, Node.js, and React web services capable of processing automated credit decisions in sub-second latency.',
      'Integrate banking verification webhooks, credit bureau soft-pull APIs, and InstaPay/PESONet disbursement rails.',
      'Implement military-grade 256-bit encryption safeguards and ensure data privacy audit readiness.',
      'Mentor junior engineers and champion test coverage, observability, and clean software architecture.',
    ],
    requirements: [
      '5+ years of production experience with TypeScript, React, Node.js, and modern SQL databases.',
      'Prior domain background in FinTech, banking APIs, payment processors (GCash/Maya/Plaid), or credit decision engines.',
      'Demonstrated expertise in building resilient RESTful and event-driven microservices.',
      'Strong knowledge of web security fundamentals (OAuth2, CORS, XSS, CSRF, Tokenization).',
    ],
    niceToHave: [
      'Experience with automated underwriting algorithms and risk scoring models.',
      'Familiarity with Cloud Run, Docker, and CI/CD pipelines.',
    ],
  },
  {
    id: 'risk-sr-underwriter',
    title: 'Senior Credit Risk Underwriter & Model Analyst',
    department: 'Credit & Risk',
    location: 'Makati City, Metro Manila',
    type: 'Full-time',
    workplace: 'Hybrid',
    salaryRange: '₱90,000 - ₱130,000 / mo + Performance Bonus',
    experience: '4+ years',
    postedDate: 'August 2026',
    featured: true,
    description: 'Refine credit risk parameters, evaluate complex commercial borrower profiles, and optimize automated debt-to-income and cash-flow underwriting models.',
    responsibilities: [
      'Analyze consumer and commercial credit applications, reviewing BIR tax filings, P&L statements, and bank cash flow records.',
      'Collaborate with the engineering team to calibrate OLAP algorithmic decision rules and minimize portfolio default rates.',
      'Ensure strict adherence to SEC financing regulations and consumer lending policies.',
      'Produce monthly credit quality dashboards and stress-testing reports for institutional capital partners.',
    ],
    requirements: [
      '4+ years of credit underwriting experience in consumer loans, SME lines of credit, or commercial financing.',
      'Comprehensive understanding of financial statement analysis, debt service coverage ratio (DSCR), and credit scoring models.',
      'High attention to regulatory compliance and Philippine lending standards.',
      'Strong analytical capabilities with SQL or advanced financial modeling in Excel.',
    ],
  },
  {
    id: 'prod-lead-designer',
    title: 'Lead Product Designer (Fintech UX/UI)',
    department: 'Product & Design',
    location: 'Taguig / BGC (or Remote PH)',
    type: 'Full-time',
    workplace: 'Remote',
    salaryRange: '₱110,000 - ₱150,000 / mo + Equity',
    experience: '4+ years',
    postedDate: 'August 2026',
    featured: false,
    description: 'Design intuitive, frictionless borrower experiences from application onboarding to real-time repayment dashboards and loan customization tools.',
    responsibilities: [
      'Own end-to-end design for the borrower web platform, loan calculator interfaces, and internal underwriting consoles.',
      'Conduct user testing sessions with borrowers to identify drop-off friction points in the application funnel.',
      'Maintain and expand our unified design system with pixel-perfect typography, accessible contrasts, and responsive layout guidelines.',
      'Partner closely with product managers and engineers to ship polished features rapidly.',
    ],
    requirements: [
      '4+ years of product design experience with a portfolio demonstrating complex web apps or fintech platforms.',
      'Deep mastery of Figma, design systems, interactive prototyping, and design tokens.',
      'Obsessive attention to accessibility (WCAG AA) and responsive micro-interactions.',
    ],
  },
  {
    id: 'ops-loan-success-manager',
    title: 'Borrower Success & Loan Operations Specialist',
    department: 'Operations',
    location: 'Makati City, Metro Manila',
    type: 'Full-time',
    workplace: 'Remote',
    salaryRange: '₱45,000 - ₱65,000 / mo + Performance Incentives',
    experience: '2+ years',
    postedDate: 'August 2026',
    featured: false,
    description: 'Deliver white-glove customer support and assist applicants through document uploads, identity verification, and funding disbursement confirmation.',
    responsibilities: [
      'Provide compassionate, swift assistance to loan applicants via live chat, phone, and secure messaging.',
      'Guide borrowers through required income documentation submissions and verify banking details for direct disbursement.',
      'Identify recurring customer pain points and provide direct feedback to the product team to improve portal UX.',
      'Maintain an industry-leading 98%+ customer satisfaction (CSAT) rating.',
    ],
    requirements: [
      '2+ years in financial services customer operations, banking support, or loan servicing.',
      'Exceptional verbal and written communication skills with high empathy and problem-solving drive.',
      'Ability to navigate modern CRM and loan origination software efficiently.',
    ],
  },
  {
    id: 'legal-compliance-officer',
    title: 'Regulatory Compliance & Lending Counsel',
    department: 'Compliance & Legal',
    location: 'Makati City, Metro Manila',
    type: 'Full-time',
    workplace: 'Hybrid',
    salaryRange: '₱140,000 - ₱190,000 / mo + Performance Bonus',
    experience: '6+ years',
    postedDate: 'August 2026',
    featured: false,
    description: 'Oversee SEC licensing maintenance, consumer protection compliance, and nationwide lending policy documentation.',
    responsibilities: [
      'Manage nationwide SEC regulatory filings, annual corporate reporting, and Anti-Money Laundering (AMLC) compliance.',
      'Review marketing copy, disclosure notices, APR calculations, and borrower loan agreements for legal compliance.',
      'Advise executive leadership on emerging fintech regulations and open-banking data privacy mandates.',
      'Conduct regular internal compliance testing and staff training programs.',
    ],
    requirements: [
      'Law degree and active Philippine Bar membership (or equivalent seasoned compliance certifications).',
      '6+ years specializing in consumer credit, banking regulations (BSP, SEC, AMLC), and fintech compliance.',
      'Experience interacting directly with financial regulatory agencies.',
    ],
  },
  {
    id: 'sales-commercial-account-exec',
    title: 'Commercial Lending Account Executive',
    department: 'Sales & Growth',
    location: 'Cebu City / Davao / Manila',
    type: 'Full-time',
    workplace: 'Remote',
    salaryRange: '₱70,000 Base (₱160,000+ OTE uncapped)',
    experience: '3+ years',
    postedDate: 'August 2026',
    featured: false,
    description: 'Drive new loan origination volume by building partnerships with small business associations, merchant cooperatives, and commercial brokers.',
    responsibilities: [
      'Source and close B2B SME expansion loans and working capital credit facilities ranging from ₱250,000 to ₱5,000,000.',
      'Establish strategic referral partnerships with CPAs, trade organizations, and business networks.',
      'Consult with business owners to understand cash flow cycles and structure optimal debt facilities.',
      'Consistently exceed quarterly loan origination quotas.',
    ],
    requirements: [
      '3+ years of proven track record in B2B financial sales, commercial lending, or fintech originations.',
      'Strong network in small business finance, commercial banking, or trade groups.',
      'Exceptional consultative presentation and negotiation abilities.',
    ],
  },
];

export const COMPANY_BENEFITS = [
  {
    title: 'Comprehensive HMO & Wellness',
    description: '100% employer-covered premium HMO medical, dental, and hospitalization coverage for you and your dependents from day 1.',
    icon: 'HeartPulse',
  },
  {
    title: 'Retirement Fund & Equity',
    description: 'Competitive salary packages paired with company equity stock options and generous retirement contributions with rapid vesting.',
    icon: 'PiggyBank',
  },
  {
    title: 'Remote-First Flexibility',
    description: 'Work flexibly from anywhere in the Philippines with a ₱50,000 home office setup allowance and monthly internet reimbursement.',
    icon: 'Laptop',
  },
  {
    title: '₱120,000 Annual Learning Budget',
    description: 'Annual dedicated budget for industry conferences, professional certifications, books, and courses to support your continuous career mastery.',
    icon: 'GraduationCap',
  },
  {
    title: 'Generous Leaves & 13th/14th Month Pay',
    description: 'Generous paid time off, 13th month guaranteed pay plus discretionary 14th-month performance bonus, and comprehensive parental leaves.',
    icon: 'CalendarCheck',
  },
  {
    title: 'Transparent Culture & Fiduciary Mission',
    description: 'Be part of a high-integrity team dedicated to eliminating predatory lending practices through fair, transparent credit access.',
    icon: 'ShieldCheck',
  },
];

export const COMPANY_VALUES = [
  {
    title: 'Radical Transparency',
    description: 'We believe zero hidden fees and clear language build lasting relationships with both our borrowers and teammates.',
  },
  {
    title: 'Algorithmic Fairness',
    description: 'Our software evaluates applicants on verifiable financial merit, actively eliminating systemic biases in credit assessment.',
  },
  {
    title: 'Fiduciary Craftsmanship',
    description: 'We build financial infrastructure with the same rigorous care, precision, and security as bank-grade custodial systems.',
  },
  {
    title: 'Borrower-First Empathy',
    description: 'Behind every loan application is a human dream, a growing business, or a family milestone. We treat every customer with deep respect.',
  },
];
