import { LoanProduct, FAQItem, Testimonial } from '@/types';

export const COMPANY_INFO = {
  name: 'ZedLendingCorp',
  platformTagline: 'Online Loan Application Processing (OLAP)',
  phone: '(02) 8876-1920',
  phoneClean: '0288761920',
  email: 'support@zedlendingcorp.com.ph',
  address: 'Zed Lending Tower, Ayala Avenue, Makati City, Metro Manila, Philippines',
  hours: 'Mon - Fri: 8:00 AM - 6:00 PM PHT, Sat: 9:00 AM - 3:00 PM PHT',
  stats: {
    yearsOfExperience: '30+',
    disbursedTotal: '₱12.5B+',
    approvalRate: '99.4%',
    turnaroundTime: '24 Hours',
    happyBorrowers: '48,000+',
    customerRating: '4.9/5',
  }
};

export const LOAN_PRODUCTS: LoanProduct[] = [
  {
    id: 'personal',
    title: 'Personal & Pension Loan',
    badge: 'Most Popular',
    tagline: 'Reliable financing for SSS/GSIS pensioners, life milestones, tuition fees, or debt consolidation.',
    minAmount: 10000,
    maxAmount: 500000,
    defaultAmount: 50000,
    minTenureMonths: 6,
    maxTenureMonths: 60,
    defaultTenureMonths: 24,
    interestRateAnnual: 5.99,
    processingFeePercent: 1.0,
    turnaroundTime: 'Same-day instant release',
    iconName: 'UserCheck',
    features: [
      'No co-maker or guarantor required',
      'Fixed monthly amortizations with zero hidden deductions',
      'Direct bank / e-wallet transfer or branch cash pickup',
      'No early repayment penalties',
    ],
    eligibility: [
      'Filipino citizen aged 21 - 70 with 2 valid IDs',
      'Stable monthly income or pension (₱15,000+/mo)',
      'Active bank account or GCash/Maya wallet',
    ],
  },
  {
    id: 'business',
    title: 'Business Expansion Loan',
    badge: 'Fast Growth',
    tagline: 'Accelerate equipment acquisition, payroll, inventory, and new branch expansion.',
    minAmount: 100000,
    maxAmount: 5000000,
    defaultAmount: 500000,
    minTenureMonths: 12,
    maxTenureMonths: 120,
    defaultTenureMonths: 36,
    interestRateAnnual: 6.75,
    processingFeePercent: 1.25,
    turnaroundTime: '1 - 2 business days',
    iconName: 'Building2',
    features: [
      'High borrowing ceiling up to ₱5,000,000',
      'Flexible amortization aligned with cash flow',
      'Tax-deductible interest structuring support',
      'Dedicated commercial loan officer',
    ],
    eligibility: [
      'At least 1 year in registered DTI / SEC business operations',
      'Annual business gross revenue > ₱800,000',
      'Bank statements for the last 6 months',
    ],
  },
  {
    id: 'sme',
    title: 'SME Working Capital',
    badge: 'Cash Flow',
    tagline: 'Smooth out supplier invoices, purchase orders, and seasonal business cycles.',
    minAmount: 50000,
    maxAmount: 1500000,
    defaultAmount: 250000,
    minTenureMonths: 3,
    maxTenureMonths: 36,
    defaultTenureMonths: 12,
    interestRateAnnual: 6.25,
    processingFeePercent: 1.0,
    turnaroundTime: 'Within 24 hours',
    iconName: 'Briefcase',
    features: [
      'Revolving credit line or term loan options',
      'Minimal paperwork and fast credit evaluation',
      'Fast liquidity for urgent supply orders',
      'Transparent weekly or monthly repayment terms',
    ],
    eligibility: [
      'Small to Medium Enterprise or sole proprietorship',
      'Monthly business turnover > ₱50,000',
      'Mayor’s Permit and Barangay Clearance',
    ],
  },
  {
    id: 'emergency',
    title: 'Emergency Cash Loan',
    badge: 'Urgent Relief',
    tagline: 'Immediate funds for medical bills, emergency home repairs, or unexpected obligations.',
    minAmount: 5000,
    maxAmount: 100000,
    defaultAmount: 25000,
    minTenureMonths: 3,
    maxTenureMonths: 24,
    defaultTenureMonths: 6,
    interestRateAnnual: 7.49,
    processingFeePercent: 0.5,
    turnaroundTime: 'As fast as 2 hours',
    iconName: 'Zap',
    features: [
      'Rapid credit assessment and minimal documents',
      'Paperless mobile submission in 3 minutes',
      'Express InstaPay or GCash/Maya disbursement',
      'Manageable short-term installments',
    ],
    eligibility: [
      '2 Valid Government IDs and proof of billing',
      'Proof of current employment or verifiable income',
    ],
  },
  {
    id: 'auto',
    title: 'Auto & Vehicle Financing',
    badge: 'Low APR',
    tagline: 'Finance brand new or second-hand cars, trucks, or refinancing at competitive rates.',
    minAmount: 100000,
    maxAmount: 2500000,
    defaultAmount: 600000,
    minTenureMonths: 12,
    maxTenureMonths: 84,
    defaultTenureMonths: 36,
    interestRateAnnual: 4.85,
    processingFeePercent: 0.75,
    turnaroundTime: 'Same-day pre-approval',
    iconName: 'Car',
    features: [
      'Competitive rates from 4.85% APR',
      'Dealership or private party vehicle purchases',
      'Flexible down payment options',
      'Fast chattel mortgage processing',
    ],
    eligibility: [
      'Vehicle under 10 years old with clean LTO OR/CR',
      'Valid Driver’s License and proof of income',
    ],
  },
  {
    id: 'home_equity',
    title: 'Home & Real Estate Financing',
    badge: 'High Value',
    tagline: 'Leverage residential real estate for home renovation, construction, or investment.',
    minAmount: 200000,
    maxAmount: 5000000,
    defaultAmount: 1000000,
    minTenureMonths: 24,
    maxTenureMonths: 180,
    defaultTenureMonths: 60,
    interestRateAnnual: 5.45,
    processingFeePercent: 1.0,
    turnaroundTime: '3 - 5 business days',
    iconName: 'Home',
    features: [
      'Substantial credit facility based on property appraisal',
      'Fixed-rate peace of mind throughout tenure',
      'Complimentary property valuation check',
      'Flexible refinancing terms',
    ],
    eligibility: [
      'Clean Transfer Certificate of Title (TCT / CCT)',
      'Updated real estate tax receipts',
    ],
  },
];

export const FAQ_LIST: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'How fast can I get loan approval and disbursement with ZedLendingCorp?',
    answer: 'Our Online Loan Application Processing (OLAP) system automates credit underwriting. For standard personal and emergency loans, you receive preliminary pre-approval within 2 minutes of submitting your inquiry. Upon document verification, funds are released via InstaPay, PESONet, e-wallet, or counter release on the same business day.',
    category: 'application',
  },
  {
    id: 'faq-2',
    question: 'Does checking my loan rate affect my credit standing?',
    answer: 'No! When you inquire or check your preliminary loan computation on our portal, there is zero impact on your credit history. Formal verification is only conducted after you proceed with the application.',
    category: 'rates',
  },
  {
    id: 'faq-3',
    question: 'What are the minimum eligibility criteria for ZedLendingCorp loans?',
    answer: 'Borrowers must be at least 21 years old (and up to 70 for pension loans), present 2 valid government IDs, have an active Philippine bank account or e-wallet, and demonstrate a regular monthly income or pension of at least ₱15,000 from verifiable sources.',
    category: 'general',
  },
  {
    id: 'faq-4',
    question: 'Are there any hidden charges or advance deduction fees?',
    answer: 'ZedLendingCorp operates with 100% SEC-compliant pricing transparency. We charge zero hidden fees, zero advance deduction charges, and no surprise penalties. The only cost is your agreed fixed APR and a clear, itemized processing fee (0.5% - 1.25%).',
    category: 'rates',
  },
  {
    id: 'faq-5',
    question: 'How do repayments work? What payment channels are available?',
    answer: 'You can repay conveniently via online banking (BDO, BPI, UnionBank, Metrobank), 7-Eleven Cliqq, GCash, Maya, Bayad Centers, or direct over-the-counter payments at any ZedLendingCorp branch.',
    category: 'repayment',
  },
  {
    id: 'faq-6',
    question: 'How does ZedLendingCorp protect my sensitive personal information?',
    answer: 'We strictly comply with Republic Act No. 10173 (Data Privacy Act of 2012) and utilize bank-grade 256-bit SSL/TLS encryption. We never share or sell your information to unauthorized third parties.',
    category: 'security',
  },
];

export const TESTIMONIALS_LIST: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Sarah Dela Cruz',
    role: 'Small Business Owner',
    company: 'Bloom Bakery & Cafe',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
    rating: 5,
    quote: 'ZedLendingCorp made our bakery expansion in Quezon City possible! While traditional banks gave us the runaround for weeks, ZedLendingCorp approved our ₱850,000 SME loan in under 24 hours. The process was fast and respectful.',
    loanType: 'Business Expansion',
    amount: '₱850,000',
  },
  {
    id: 'test-2',
    name: 'Marcus Villanueva',
    role: 'IT Project Manager',
    company: 'Apex Tech Solutions',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
    rating: 5,
    quote: 'I consolidated multiple high-interest credit card debts into one single affordable monthly payment at a low interest rate. I am saving over ₱4,500 each month. Outstanding customer service!',
    loanType: 'Personal Loan',
    amount: '₱300,000',
  },
  {
    id: 'test-3',
    name: 'Elena Santos',
    role: 'Government Pensioner',
    company: 'GSIS / DepEd Retiree',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80',
    rating: 5,
    quote: 'When my family had an urgent medical emergency, ZedLendingCorp came through with an emergency cash loan of ₱65,000 in just 4 hours. No complicated requirements and respectful staff. 10/10.',
    loanType: 'Emergency Cash',
    amount: '₱65,000',
  },
];

export const DEMO_USER = {
  id: 'usr_zed_001',
  email: 'maria.santos@example.ph',
  fullName: 'Maria Santos',
  phone: '(02) 8876-1920',
  avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=256&q=80',
  memberSince: 'March 2023',
  creditScore: 745,
  isVerified: true,
  activeLoanCount: 1,
};
