# Generated by Django 5.2.5 on 2026-05-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=100)),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "base_interest_rate",
                    models.DecimalField(decimal_places=4, max_digits=8),
                ),
                ("max_term_months", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
