FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
        build-essential \
        curl \
        supervisor \
        && rm -rf /var/lib/apt/lists/*

COPY ./requirements/base.txt /app/
RUN pip install --upgrade pip && pip install --no-cache-dir -r base.txt

COPY . .

EXPOSE 8000

CMD ["supervisord", "-c", "/app/supervisord.conf"]
