export const countries = [
    { name: 'United States', code: 'US', dial_code: '+1', phone_length: 10 },
    { name: 'United Kingdom', code: 'GB', dial_code: '+44', phone_length: 10 },
    { name: 'Australia', code: 'AU', dial_code: '+61', phone_length: 9 },
    { name: 'New Zealand', code: 'NZ', dial_code: '+64', phone_length: 9 },
    { name: 'Canada', code: 'CA', dial_code: '+1', phone_length: 10 },
    { name: 'India', code: 'IN', dial_code: '+91', phone_length: 10 },
    { name: 'Germany', code: 'DE', dial_code: '+49', phone_length: 11 },
    { name: 'France', code: 'FR', dial_code: '+33', phone_length: 9 },
    { name: 'Brazil', code: 'BR', dial_code: '+55', phone_length: 11 },
    { name: 'China', code: 'CN', dial_code: '+86', phone_length: 11 },
    { name: 'Japan', code: 'JP', dial_code: '+81', phone_length: 10 },
    { name: 'Mexico', code: 'MX', dial_code: '+52', phone_length: 10 },
    { name: 'Philippines', code: 'PH', dial_code: '+63', phone_length: 10 },
    { name: 'Russia', code: 'RU', dial_code: '+7', phone_length: 10 },
    { name: 'Afghanistan', code: 'AF', dial_code: '+93', phone_length: 9 },
    { name: 'Albania', code: 'AL', dial_code: '+355', phone_length: 9 },
    { name: 'Algeria', code: 'DZ', dial_code: '+213', phone_length: 9 },
    { name: 'Andorra', code: 'AD', dial_code: '+376', phone_length: 6 },
    { name: 'Angola', code: 'AO', dial_code: '+244', phone_length: 9 },
    { name: 'Argentina', code: 'AR', dial_code: '+54', phone_length: 10 },
];
